
import Head from 'next/head'

import { words, regularVerbs, irregularVerbs, phrasalVerbs, verbToBe, auxiliarVerbs } from "../../mg/english";

import Words from "../../Components/Words";
import styles from './palabras.module.css';


const Palabras = () => {

    const allWords = [...words, ...verbToBe, ...auxiliarVerbs, ...regularVerbs, ...irregularVerbs, ...phrasalVerbs];

    return (
        <div className={styles.home}>
            <Head>
                <meta charSet="UTF-8" />
                <meta name="description" content="Generated by create next app" />
                <meta httpEquiv="Content-Language" content="en" />
                <link rel="icon" href="/favicon.ico" />
                <title>Palabras en inglés</title>
            </Head>

            <div className={styles.words_container}>
                <div className={styles.titles}>
                    <span className={styles.word}>Palabra</span>
                    <span className={styles.pronunciation_t}>Pronunciación</span>
                    <span className={styles.meaning}>Significado</span>
                </div>
            </div>

            {allWords.map((element, index) => {
                return <Words word={element} index={index} key={index} />;
            })}
        </div>
    );
};

export default Palabras;