
import Head from 'next/head';

import styles from './introduction.module.css';


const Introduction = () => {

    return (
        <div className={styles.introduction}>
            <Head>
                <meta charSet="UTF-8" />
                <meta name="description" content="Generated by create next app" />
                <meta httpEquiv="Content-Language" content="es" />
                <link rel="icon" href="/favicon.ico" />
                <title>Introducción</title>
            </Head>

            <div>
                Introduction.
            </div>
        </div>

    );
}


export default Introduction;

